### PR TITLE
Arduino compatibility

### PR DESCRIPTION
**Pull request by lasselukkari**
Hi, thanks for  the lib!

I wanted to try it out with Arduino Uno + Ethernet Shield and did a few modifications. The biggest change is that it now uses the Client interface. This makes it compatible with the various other arduino tcp client implementations. At least publishing is working fine using the Arduino Uno and W5100. I also tested that it still compiles with the Particle Build

### CODE REVIEW

**Comment by isobit** [comment]
Interesting, I did not realize that the Arduino platform itself does not support `asprintf`, unfortunately the ESP8266 doesn't support `sprintf` (only `asprintf`), so maybe we can add a `asprintf` shim for Arduino. 

Same thing goes for the ethernet TCP client, the ESP8266 doesn't define the client in the same way (with a `client.h` file), so this would break compatibility for that. What if we allowed overriding `TCPClient` with the following?

``` c++
#include "Arduino.h"
#ifndef TCPClient 
#define TCPClient WiFiClient
#endif
...
#endif
```

That way in your `main.ino` you could do:

``` c++
#define TCPClient Client
#include "nats.hpp"
```

**Comment by isobit** [comment]
Another option which might be more scalable would be to define a proxy `TCPClient` class which is a standard interface to the platform-specific clients which could also be overridden. It would be more verbose but would cover the case that a client has different method signatures. Let me know what you think.

**Comment by lasselukkari** [comment]
If something has not changed just recently the Client interface works just fine with the Arduino port of ESP8266. Also works with Teensy.

**Comment by lasselukkari** [comment]
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/WiFiClient.h#L27
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/WiFiClient.h#L36

**Comment by lasselukkari** [comment]
As the asprintf is used only once I think we could live without any format helper functions. The client connection could also be handled outside the lib.

**Comment by isobit** [comment]
Oh, I didn't realize, I understand now. I'll fix the `asprintf` issue and then merge in your pull request 👍

**Comment by lasselukkari** [comment]
I'm unable to upload the sketch to a esp8266 at moment because i can't find a proper usb cable. But with the Esp8266 selected in the IDE I get no complaints about the sprintf when I compile it. What versions ide and esp8266 core you have installed?

**Comment by lasselukkari** [comment]
What version of esp8266 core and the IDE you have installed? They seem to be using sprintf in their [examples](https://github.com/esp8266/Arduino/blob/633e48f3aec5f1c3c11d4498fc90d378d49e6e9f/libraries/ESP8266WiFiMesh/examples/HelloMesh/HelloMesh.ino#L26). Can't upload to a esp8266 at the moment but at least the compiling passes.

**Comment by isobit** [comment]
I realized that function shouldn't have been using `asprintf` anyway, that was the one that didn't work on the ESP8266 (oops). So yeah `sprintf` is fine, but I changed it to `snprintf` anyway just to be (redundantly) sure about out-of-bounds writing. Thanks for the contribution!

**Pull request merged**
